# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QotKljL0enLRlmL6sYU77SAxJ640xhjH
"""

import os
import re
from flask import Flask, request, abort
from linebot import LineBotApi, WebhookHandler
from linebot.exceptions import InvalidSignatureError
from linebot.models import MessageEvent, TextMessage, TextSendMessage
from youtube_transcript_api import YouTubeTranscriptApi
import google.generativeai as genai

app = Flask(__name__)

# ==========================================
# 設定區：從 Render 的環境變數讀取 Key
# ==========================================
# 這些變數需要在 Render 的 Dashboard 中設定，不要直接寫在程式碼裡
LINE_CHANNEL_ACCESS_TOKEN = os.environ.get('LINE_CHANNEL_ACCESS_TOKEN')
LINE_CHANNEL_SECRET = os.environ.get('LINE_CHANNEL_SECRET')
GOOGLE_API_KEY = os.environ.get('GOOGLE_API_KEY')

# 初始化 LINE Bot
if LINE_CHANNEL_ACCESS_TOKEN is not None:
    line_bot_api = LineBotApi(LINE_CHANNEL_ACCESS_TOKEN)
    handler = WebhookHandler(LINE_CHANNEL_SECRET)
else:
    # 避免本地測試時若沒有設環境變數會直接報錯，這裡做個簡單防呆
    print("警告：未讀取到 LINE Token，請確認環境變數是否設定。")
    line_bot_api = None
    handler = None

# 初始化 Google Gemini
if GOOGLE_API_KEY:
    genai.configure(api_key=GOOGLE_API_KEY)
    model = genai.GenerativeModel('gemini-1.5-flash')
else:
    print("警告：未讀取到 Google API Key。")

# ==========================================
# 路由區
# ==========================================

# 1. 健康檢查路由 (讓 Render 知道程式還活著，也給 UptimeRobot 用)
@app.route("/")
def home():
    return "Hello, Line Bot is running! (Youtube Summary Bot)"

# 2. LINE Webhook 入口
@app.route("/callback", methods=['POST'])
def callback():
    if handler is None:
        return 'Error: LINE Bot config is missing', 500

    signature = request.headers['X-Line-Signature']
    body = request.get_data(as_text=True)
    try:
        handler.handle(body, signature)
    except InvalidSignatureError:
        abort(400)
    return 'OK'

# ==========================================
# 邏輯區
# ==========================================

# 確保 handler 存在才註冊事件 (避免本地沒設 Key 時報錯)
if handler:
    @handler.add(MessageEvent, message=TextMessage)
    def handle_message(event):
        msg = event.message.text

        # 使用正規表達式檢查是否包含 YouTube 連結
        youtube_pattern = r'(https?://)?(www\.)?(youtube\.com|youtu\.be)/[\w-]+'
        match = re.search(youtube_pattern, msg)

        if match:
            video_url = match.group(0)
            print(f"收到影片連結: {video_url}")

            try:
                # 1. 取得 Video ID
                video_id = extract_video_id(video_url)

                # 2. 抓取字幕 (嘗試抓取繁中、簡中、英文)
                # 注意：如果影片完全沒有 CC 字幕，這一步會報錯
                transcript_list = YouTubeTranscriptApi.get_transcript(
                    video_id,
                    languages=['zh-TW', 'zh-Hant', 'zh-CN', 'zh-Hans', 'en']
                )

                # 3. 組合字幕文字
                full_text = " ".join([t['text'] for t in transcript_list])

                # 4. 呼叫 Gemini 進行摘要
                if not GOOGLE_API_KEY:
                    reply_text = "錯誤：伺服器端未設定 Google API Key，無法進行摘要。"
                else:
                    reply_text = get_gemini_summary(full_text)

                # 5. 回覆 LINE
                line_bot_api.reply_message(
                    event.reply_token,
                    TextSendMessage(text=f"📺 影片摘要：\n\n{reply_text}")
                )

            except Exception as e:
                print(f"Error processing video: {e}")
                error_msg = "無法取得字幕，可能是該影片沒有提供 CC 字幕功能，或是連結無效。"
                line_bot_api.reply_message(
                    event.reply_token,
                    TextSendMessage(text=error_msg)
                )

def extract_video_id(url):
    """從網址中提取 YouTube Video ID"""
    if "youtu.be" in url:
        return url.split("/")[-1].split("?")[0]
    else:
        # 處理 watch?v= 以及可能存在的其他參數
        try:
            return url.split("v=")[1].split("&")[0]
        except:
            return url.split("/")[-1]

def get_gemini_summary(text):
    """呼叫 Google Gemini API 產生摘要"""
    prompt = f"""
    你是一個專業的影片摘要助手。
    請閱讀以下的影片字幕，並用繁體中文完成以下任務：
    1. 【標題】：用一句話概括影片主旨。
    2. 【重點】：列出 3-5 個關鍵重點 (使用條列式，並加上適當的 emoji)。
    3. 【結論】：給出一個簡短的總結。

    ---
    影片字幕內容：
    {text}
    """
    try:
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"AI 摘要生成失敗: {str(e)}"

if __name__ == "__main__":
    app.run()